FROM node:lts-alpine3.19 as base

# Development Stage

FROM base AS dev

RUN apk add --no-cache libc6-compat

RUN npm install -g npm@latest

WORKDIR /frontend-dev

CMD [ "/bin/sh", "-c", "npm install && npm run dev" ]